#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap.php';

if (!class_exists(\Gatovel\Cli\Application::class)) {
    fwrite(
        STDERR,
        "Gatovel CLI is not installed." . PHP_EOL
        . "Install it with: composer require gatovel/cli:^2.0"
        . PHP_EOL
    );

    exit(1);
}

$application = new \Gatovel\Cli\Application();

exit(
    $application->run($argv)
);
